services:
  - type: web
    name: kers0neprotector
    runtime: docker
    repo: https://github.com/kers0nec/kers0neprotector
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
